#ifndef MYSHAREDLIBRARY_GLOBAL_H
#define MYSHAREDLIBRARY_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(MYSHAREDLIBRARY_LIBRARY)
#  define MYSHAREDLIBRARYSHARED_EXPORT Q_DECL_EXPORT
#else
#  define MYSHAREDLIBRARYSHARED_EXPORT Q_DECL_IMPORT
#endif

#endif // MYSHAREDLIBRARY_GLOBAL_H
